#!/usr/bin/env bash
# Regenerate docs/llms-full.txt by concatenating every .md page under docs/.
#
# Run whenever docs/ changes (CLAUDE.md rule #10). Output is deterministic —
# files are walked in lexical order and separated by a boundary header so an
# LLM can slice the corpus back into pages.
#
# Usage:
#   scripts/gen-llms-txt.sh           # regenerate docs/llms-full.txt
#   scripts/gen-llms-txt.sh --check   # exit non-zero if output would change
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
docs_dir="$repo_root/docs"
out_file="$docs_dir/llms-full.txt"

if [[ ! -d "$docs_dir" ]]; then
  echo "gen-llms-txt: docs/ not found at $docs_dir" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'HEADER'
# Translately — full documentation corpus

> Auto-generated by `scripts/gen-llms-txt.sh`. Do not hand-edit — every edit to a `docs/**.md` file regenerates this file. The generator walks `docs/` in stable order, skips `llms.txt` and `llms-full.txt` themselves, and concatenates each page with a header boundary so an LLM can slice it back into sections.

<!-- BEGIN: generated content -->

HEADER

  # LC_ALL=C sort gives a stable order across macOS and Linux.
  while IFS= read -r -d '' file; do
    rel="${file#$docs_dir/}"
    printf '\n\n<!-- ===== FILE: %s ===== -->\n\n' "$rel"
    cat "$file"
  done < <(find "$docs_dir" -type f -name '*.md' \
    ! -name 'llms-full.txt' ! -name 'llms.txt' -print0 \
    | LC_ALL=C sort -z)

  cat <<'FOOTER'

<!-- END: generated content -->
FOOTER
} > "$tmp"

if [[ "${1-}" == "--check" ]]; then
  if ! diff -q "$tmp" "$out_file" > /dev/null 2>&1; then
    echo "gen-llms-txt: docs/llms-full.txt is out of date. Run scripts/gen-llms-txt.sh." >&2
    exit 1
  fi
  exit 0
fi

mv "$tmp" "$out_file"
trap - EXIT
echo "gen-llms-txt: wrote $out_file"
