build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 30
    thresholdInClasses: 20
    thresholdInObjects: 15
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 8
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 4
  UnusedPrivateMember:
    active: true
  UseCheckOrError:
    active: true

naming:
  FunctionNaming:
    active: true
    functionPattern: "[a-z][a-zA-Z0-9]*"
  VariableNaming:
    active: true
    variablePattern: "[a-z][a-zA-Z0-9]*"

performance:
  SpreadOperator:
    active: true
  ArrayPrimitive:
    active: true

potential-bugs:
  ImplicitDefaultLocale:
    active: true
  UnsafeCallOnNullableType:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
  SwallowedException:
    active: true
